--
-- PostgreSQL database dump
--

\restrict epOvU7BJGnbunQehlFKkox4ZqZODlUql0XGtIqqxXX9zQceBqPkexbqFgisXWZE

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings_booking (
    id bigint NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    total_price numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    cancelled_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.bookings_booking OWNER TO postgres;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: food_fooditem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_fooditem (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    category character varying(20) NOT NULL,
    price numeric(10,2) NOT NULL,
    image_url character varying(200) NOT NULL,
    available boolean NOT NULL,
    preparation_time integer NOT NULL,
    is_vegetarian boolean NOT NULL,
    is_vegan boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.food_fooditem OWNER TO postgres;

--
-- Name: food_fooditem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food_fooditem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_fooditem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_foodorder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_foodorder (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    special_instructions text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.food_foodorder OWNER TO postgres;

--
-- Name: food_foodorder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food_foodorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_foodorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price_at_order numeric(10,2) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    food_item_id bigint NOT NULL,
    food_order_id bigint NOT NULL
);


ALTER TABLE public.food_orderitem OWNER TO postgres;

--
-- Name: food_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    transaction_id character varying(100) NOT NULL,
    razorpay_order_id character varying(100),
    razorpay_payment_id character varying(100),
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    payment_method character varying(20) NOT NULL,
    payment_date timestamp with time zone,
    refund_amount numeric(10,2) NOT NULL,
    refund_date timestamp with time zone,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    booking_id bigint,
    food_order_id bigint
);


ALTER TABLE public.payments_payment OWNER TO postgres;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms_room (
    id bigint NOT NULL,
    room_number character varying(10) NOT NULL,
    room_type character varying(20) NOT NULL,
    price_per_night numeric(10,2) NOT NULL,
    capacity integer NOT NULL,
    description text NOT NULL,
    is_available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.rooms_room OWNER TO postgres;

--
-- Name: rooms_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(15) NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add room	7	add_room
26	Can change room	7	change_room
27	Can delete room	7	delete_room
28	Can view room	7	view_room
29	Can add booking	8	add_booking
30	Can change booking	8	change_booking
31	Can delete booking	8	delete_booking
32	Can view booking	8	view_booking
33	Can add food order	10	add_foodorder
34	Can change food order	10	change_foodorder
35	Can delete food order	10	delete_foodorder
36	Can view food order	10	view_foodorder
37	Can add order item	11	add_orderitem
38	Can change order item	11	change_orderitem
39	Can delete order item	11	delete_orderitem
40	Can view order item	11	view_orderitem
41	Can add food item	9	add_fooditem
42	Can change food item	9	change_fooditem
43	Can delete food item	9	delete_fooditem
44	Can view food item	9	view_fooditem
45	Can add payment	12	add_payment
46	Can change payment	12	change_payment
47	Can delete payment	12	delete_payment
48	Can view payment	12	view_payment
\.


--
-- Data for Name: bookings_booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bookings_booking (id, check_in_date, check_out_date, total_price, created_at, room_id, user_id, status, cancelled_at, updated_at) FROM stdin;
5	2025-06-13	2025-06-14	5000.00	2026-05-13 15:53:21.359199+05:30	1	1	cancelled	2026-05-13 17:46:33.054548+05:30	2026-05-17 09:31:06.468839+05:30
6	2026-06-14	2026-06-15	5000.00	2026-05-14 10:22:05.108989+05:30	1	1	cancelled	2026-05-15 11:09:30.738241+05:30	2026-05-17 09:31:06.468839+05:30
7	2026-06-15	2026-06-16	5000.00	2026-05-15 10:57:02.440715+05:30	1	1	cancelled	2026-05-15 11:09:35.214906+05:30	2026-05-17 09:31:06.468839+05:30
8	2026-11-12	2026-11-13	5000.00	2026-05-15 11:09:54.05787+05:30	1	1	confirmed	\N	2026-05-17 09:31:06.468839+05:30
9	2026-01-12	2026-01-13	5000.00	2026-05-15 11:44:54.784762+05:30	2	1	confirmed	\N	2026-05-17 09:31:06.468839+05:30
10	2026-05-12	2026-05-13	5000.00	2026-05-16 13:45:38.378337+05:30	2	1	confirmed	\N	2026-05-17 09:31:06.468839+05:30
11	2026-12-13	2026-12-14	5650.00	2026-05-17 07:22:37.402134+05:30	1	1	confirmed	\N	2026-05-17 09:31:06.468839+05:30
12	2026-12-11	2026-12-12	5000.00	2026-05-17 09:12:20.4885+05:30	1	1	confirmed	\N	2026-05-17 09:31:06.468839+05:30
13	2025-12-11	2025-12-12	5000.00	2026-05-17 09:16:18.702274+05:30	1	4	cancelled	2026-05-17 09:35:42.038027+05:30	2026-05-17 09:35:42.038205+05:30
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-13 10:30:20.709677+05:30	1	101	1	[{"added": {}}]	7	2
2	2026-05-13 10:31:13.790305+05:30	2	201	1	[{"added": {}}]	7	2
3	2026-05-13 10:31:40.736284+05:30	3	301	1	[{"added": {}}]	7	2
4	2026-05-13 10:32:23.536518+05:30	4	202	1	[{"added": {}}]	7	2
5	2026-05-13 10:32:29.442884+05:30	4	202	2	[]	7	2
6	2026-05-13 15:50:26.374618+05:30	4	customer1 - 101	3		8	2
7	2026-05-13 15:50:36.607786+05:30	2	customer1 - 101	3		8	2
8	2026-05-13 15:50:44.323807+05:30	3	customer1 - 201	3		8	2
9	2026-05-13 15:50:50.116942+05:30	1	customer1 - 101	3		8	2
10	2026-05-14 11:44:39.569077+05:30	1	Chicken beriany	1	[{"added": {}}]	9	2
11	2026-05-14 11:52:16.171228+05:30	2	Paneer Butter masala	1	[{"added": {}}]	9	2
12	2026-05-14 11:53:03.035124+05:30	1	Chicken biryani	2	[{"changed": {"fields": ["Name"]}}]	9	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	rooms	room
8	bookings	booking
9	food	fooditem
10	food	foodorder
11	food	orderitem
12	payments	payment
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-12 11:48:46.396422+05:30
2	contenttypes	0002_remove_content_type_name	2026-05-12 11:48:46.402735+05:30
3	auth	0001_initial	2026-05-12 11:48:46.44008+05:30
4	auth	0002_alter_permission_name_max_length	2026-05-12 11:48:46.444385+05:30
5	auth	0003_alter_user_email_max_length	2026-05-12 11:48:46.449336+05:30
6	auth	0004_alter_user_username_opts	2026-05-12 11:48:46.453779+05:30
7	auth	0005_alter_user_last_login_null	2026-05-12 11:48:46.459544+05:30
8	auth	0006_require_contenttypes_0002	2026-05-12 11:48:46.461152+05:30
9	auth	0007_alter_validators_add_error_messages	2026-05-12 11:48:46.468327+05:30
10	auth	0008_alter_user_username_max_length	2026-05-12 11:48:46.472588+05:30
11	auth	0009_alter_user_last_name_max_length	2026-05-12 11:48:46.476232+05:30
12	auth	0010_alter_group_name_max_length	2026-05-12 11:48:46.481487+05:30
13	auth	0011_update_proxy_permissions	2026-05-12 11:48:46.486889+05:30
14	auth	0012_alter_user_first_name_max_length	2026-05-12 11:48:46.491211+05:30
15	users	0001_initial	2026-05-12 11:48:46.542887+05:30
16	admin	0001_initial	2026-05-12 11:48:46.569501+05:30
17	admin	0002_logentry_remove_auto_add	2026-05-12 11:48:46.575413+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-05-12 11:48:46.582375+05:30
19	sessions	0001_initial	2026-05-12 11:48:46.594475+05:30
20	rooms	0001_initial	2026-05-13 10:17:37.888528+05:30
21	bookings	0001_initial	2026-05-13 11:30:26.438834+05:30
22	bookings	0002_booking_status	2026-05-13 17:43:56.720065+05:30
23	food	0001_initial	2026-05-14 10:43:13.352321+05:30
24	bookings	0003_remove_booking_is_confirmed_booking_updated_at_and_more	2026-05-17 09:31:06.521053+05:30
25	payments	0001_initial	2026-05-17 09:31:06.583388+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
wrahuj9wrwuq0fl6t7t6z12t0qnj6tnd	.eJxVjMsOgjAQAP9lz6YpW2ArR-98A2n3YVEDCY-T8d8NCQe9zkzmDUPatzLsqy7DKNABwuWX5cRPnQ4hjzTdZ8fztC1jdkfiTru6fhZ93c72b1DSWqCDzCjeUnWtQyMtk5I3C42FioQVY5MRMRsnJgoordVKrNGieSJVD58vAVk4zA:1wMi0F:wGt9QHFs2mKLzcSPeqHZ7dbvmTZ3_PK6jxv6GImv5ms	2026-05-26 13:28:07.632421+05:30
5em2joo9j90yc8rnj2qri7oto2s9ua82	.eJxVjMsOgjAQAP9lz6YpW2ArR-98A2n3YVEDCY-T8d8NCQe9zkzmDUPatzLsqy7DKNABwuWX5cRPnQ4hjzTdZ8fztC1jdkfiTru6fhZ93c72b1DSWqCDzCjeUnWtQyMtk5I3C42FioQVY5MRMRsnJgoordVKrNGieSJVD58vAVk4zA:1wN1bj:kQ0JJm48wZeZPfxjPTIAfFExTWI-pAydwPo8wq_Wm6Y	2026-05-27 10:24:07.805402+05:30
uzfaa0l2tbvrrdi9qbq9ztxch1xtneh3	.eJxVjMsOgjAQAP9lz6YpW2ArR-98A2n3YVEDCY-T8d8NCQe9zkzmDUPatzLsqy7DKNABwuWX5cRPnQ4hjzTdZ8fztC1jdkfiTru6fhZ93c72b1DSWqCDzCjeUnWtQyMtk5I3C42FioQVY5MRMRsnJgoordVKrNGieSJVD58vAVk4zA:1wN1dF:DS5BXdP19u01xj7U8sVDNppbIP6YWnSwG-A5laLeMVU	2026-05-27 10:25:41.910848+05:30
\.


--
-- Data for Name: food_fooditem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_fooditem (id, name, description, category, price, image_url, available, preparation_time, is_vegetarian, is_vegan, created_at, updated_at) FROM stdin;
2	Paneer Butter masala	A famous vegetarian food item	veg_main	350.00	https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=1000	t	15	t	f	2026-05-14 11:52:16.168765+05:30	2026-05-14 11:52:16.168789+05:30
1	Chicken biryani	a rice category food item ,with spices and chicken	rice	300.00	https://images.unsplash.com/photo-1701579231349-d7459c40919d?q=80&w=1000	t	15	f	t	2026-05-14 11:44:39.563607+05:30	2026-05-14 11:53:03.028032+05:30
\.


--
-- Data for Name: food_foodorder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_foodorder (id, status, total_price, special_instructions, created_at, updated_at, user_id) FROM stdin;
1	cancelled	950.00	Deliver quickly	2026-05-14 11:59:23.310767+05:30	2026-05-14 12:00:46.656167+05:30	1
3	cancelled	650.00		2026-05-15 08:42:08.966617+05:30	2026-05-15 11:00:41.70734+05:30	1
2	cancelled	650.00		2026-05-14 12:24:16.568428+05:30	2026-05-15 11:00:45.430083+05:30	1
4	order_confirmed	1250.00		2026-05-15 11:04:07.014714+05:30	2026-05-15 11:04:07.014737+05:30	1
5	order_confirmed	650.00		2026-05-15 11:24:08.854016+05:30	2026-05-15 11:24:08.854032+05:30	1
6	order_confirmed	650.00		2026-05-15 11:29:26.501219+05:30	2026-05-15 11:29:26.50124+05:30	1
7	order_confirmed	650.00		2026-05-17 07:13:31.281438+05:30	2026-05-17 07:13:31.281469+05:30	1
8	order_confirmed	650.00		2026-05-17 07:22:37.471075+05:30	2026-05-17 07:22:37.471096+05:30	1
9	order_confirmed	600.00		2026-05-17 08:58:40.010536+05:30	2026-05-17 08:58:40.010573+05:30	1
10	cancelled	700.00		2026-05-17 09:44:42.417064+05:30	2026-05-17 09:45:18.013084+05:30	4
\.


--
-- Data for Name: food_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_orderitem (id, quantity, price_at_order, notes, created_at, food_item_id, food_order_id) FROM stdin;
1	2	300.00	Less spicy	2026-05-14 11:59:23.322613+05:30	1	1
2	1	350.00		2026-05-14 11:59:23.326417+05:30	2	1
3	1	350.00		2026-05-14 12:24:16.573293+05:30	2	2
4	1	300.00		2026-05-14 12:24:16.576907+05:30	1	2
5	1	350.00		2026-05-15 08:42:08.989303+05:30	2	3
6	1	300.00		2026-05-15 08:42:08.994773+05:30	1	3
7	1	350.00		2026-05-15 11:04:07.020844+05:30	2	4
8	3	300.00		2026-05-15 11:04:07.025234+05:30	1	4
9	1	350.00		2026-05-15 11:24:08.866476+05:30	2	5
10	1	300.00		2026-05-15 11:24:08.870514+05:30	1	5
11	1	350.00		2026-05-15 11:29:26.505074+05:30	2	6
12	1	300.00		2026-05-15 11:29:26.509215+05:30	1	6
13	1	350.00		2026-05-17 07:13:31.288787+05:30	2	7
14	1	300.00		2026-05-17 07:13:31.292936+05:30	1	7
15	1	350.00		2026-05-17 07:22:37.474861+05:30	2	8
16	1	300.00		2026-05-17 07:22:37.478092+05:30	1	8
17	2	300.00		2026-05-17 08:58:40.014957+05:30	1	9
18	2	350.00		2026-05-17 09:44:42.42281+05:30	2	10
\.


--
-- Data for Name: payments_payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments_payment (id, transaction_id, razorpay_order_id, razorpay_payment_id, amount, status, payment_method, payment_date, refund_amount, refund_date, notes, created_at, updated_at, booking_id, food_order_id) FROM stdin;
\.


--
-- Data for Name: rooms_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rooms_room (id, room_number, room_type, price_per_night, capacity, description, is_available, created_at) FROM stdin;
1	101	single	2000.00	2	Comfortable single room with AC, WiFi, and attached bathroom.	t	2026-05-13 10:30:20.705822+05:30
2	201	double	3500.00	4	Spacious double room suitable for families	t	2026-05-13 10:31:13.789124+05:30
3	301	suite	4000.00	4	Luxury suite with premium interior and balcony	t	2026-05-13 10:31:40.734899+05:30
4	202	double	4000.00	4	Spacious double room suitable for families	t	2026-05-13 10:32:23.53517+05:30
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, phone_number, role) FROM stdin;
1	pbkdf2_sha256$1200000$XVceQmPGn9kGGf3n8PFGde$Pw7l9h4d6nWhNf2UiUbLtCcQIxoaYEiG1Dq74K9jqJY=	\N	f	customer1			f	t	2026-05-12 12:00:33.247946+05:30	customer1@gmail.com	9876543210	customer
3	pbkdf2_sha256$1200000$jphhAmHnu2Z68boRpNw55m$DnQH6uL6O2c2HQrTKxfG2lhZR1HQPPq90KNuE9M852k=	\N	t	admin2			t	t	2026-05-12 13:23:50.635264+05:30	admin2@gmail.com		customer
2	pbkdf2_sha256$1200000$eP9AzdAaBJzyS1GLkP08zG$D/xYXRoDWQ27058z5piRAjBWbTEO0F/UyGXs3uawuMg=	2026-05-13 10:25:41.906629+05:30	t	admin123			t	t	2026-05-12 13:07:52.874881+05:30	admin1@gmail.com		customer
4	pbkdf2_sha256$1200000$0UUQtbs1hr05KZdAV9KDXP$OE+aEUu9wLKRAVMnJnvLL0fdrdA7yLxjTrHcO9dpx4k=	\N	f	customer2			f	t	2026-05-13 17:00:36.84943+05:30	customer2@gmail.com	9543210532	customer
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: bookings_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bookings_booking_id_seq', 13, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 12, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: food_fooditem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_fooditem_id_seq', 2, true);


--
-- Name: food_foodorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_foodorder_id_seq', 10, true);


--
-- Name: food_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_orderitem_id_seq', 18, true);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 1, false);


--
-- Name: rooms_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rooms_room_id_seq', 4, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 4, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: bookings_booking bookings_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: food_fooditem food_fooditem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_fooditem
    ADD CONSTRAINT food_fooditem_pkey PRIMARY KEY (id);


--
-- Name: food_foodorder food_foodorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_foodorder
    ADD CONSTRAINT food_foodorder_pkey PRIMARY KEY (id);


--
-- Name: food_orderitem food_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_orderitem
    ADD CONSTRAINT food_orderitem_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_transaction_id_key UNIQUE (transaction_id);


--
-- Name: rooms_room rooms_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms_room
    ADD CONSTRAINT rooms_room_pkey PRIMARY KEY (id);


--
-- Name: rooms_room rooms_room_room_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms_room
    ADD CONSTRAINT rooms_room_room_number_key UNIQUE (room_number);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: bookings_booking_room_id_6f0fa517; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_room_id_6f0fa517 ON public.bookings_booking USING btree (room_id);


--
-- Name: bookings_booking_user_id_834dfc23; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_user_id_834dfc23 ON public.bookings_booking USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: food_foodorder_user_id_38697a71; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX food_foodorder_user_id_38697a71 ON public.food_foodorder USING btree (user_id);


--
-- Name: food_orderitem_food_item_id_c811ffaf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX food_orderitem_food_item_id_c811ffaf ON public.food_orderitem USING btree (food_item_id);


--
-- Name: food_orderitem_food_order_id_bd3298c9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX food_orderitem_food_order_id_bd3298c9 ON public.food_orderitem USING btree (food_order_id);


--
-- Name: payments_payment_booking_id_2a46974b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payments_payment_booking_id_2a46974b ON public.payments_payment USING btree (booking_id);


--
-- Name: payments_payment_food_order_id_fd4af375; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payments_payment_food_order_id_fd4af375 ON public.payments_payment USING btree (food_order_id);


--
-- Name: payments_payment_transaction_id_55f6af3a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payments_payment_transaction_id_55f6af3a_like ON public.payments_payment USING btree (transaction_id varchar_pattern_ops);


--
-- Name: rooms_room_room_number_bdf83a87_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX rooms_room_room_number_bdf83a87_like ON public.rooms_room USING btree (room_number varchar_pattern_ops);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_room_id_6f0fa517_fk_rooms_room_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_room_id_6f0fa517_fk_rooms_room_id FOREIGN KEY (room_id) REFERENCES public.rooms_room(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_user_id_834dfc23_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_user_id_834dfc23_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: food_foodorder food_foodorder_user_id_38697a71_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_foodorder
    ADD CONSTRAINT food_foodorder_user_id_38697a71_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: food_orderitem food_orderitem_food_item_id_c811ffaf_fk_food_fooditem_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_orderitem
    ADD CONSTRAINT food_orderitem_food_item_id_c811ffaf_fk_food_fooditem_id FOREIGN KEY (food_item_id) REFERENCES public.food_fooditem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: food_orderitem food_orderitem_food_order_id_bd3298c9_fk_food_foodorder_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_orderitem
    ADD CONSTRAINT food_orderitem_food_order_id_bd3298c9_fk_food_foodorder_id FOREIGN KEY (food_order_id) REFERENCES public.food_foodorder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_booking_id_2a46974b_fk_bookings_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_booking_id_2a46974b_fk_bookings_booking_id FOREIGN KEY (booking_id) REFERENCES public.bookings_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_food_order_id_fd4af375_fk_food_foodorder_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_food_order_id_fd4af375_fk_food_foodorder_id FOREIGN KEY (food_order_id) REFERENCES public.food_foodorder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict epOvU7BJGnbunQehlFKkox4ZqZODlUql0XGtIqqxXX9zQceBqPkexbqFgisXWZE

